name: Publish
on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-20.04
    name: Run style/security checks & tests
    container:
      image: node:16-slim
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn -v
          yarn

      - name: Publish to NPM
        run: yarn auto shipit
